### ISSUE TITLE
Doesn't work in Safari 6.0.2 (mac)

### ISSUE THREAD

**Issue by joshuawagner** [WilDoane/Pinboard-Bulk-Tag-Editor#2]
I use your software regularly and I'd love to be able to use it on my new computer too but since I upgraded I can't seem to get it to work. Is there a fix available?

**Comment by WilDoane** [comment]
Can you be more specific? I just used it in OSX 10.8.2, Safari 6.0.2 successfully. I did note that the tags weren't in alphabetical order, and will look into that. However, changes made to tags and submitted seemed to update my tags on Pinboard successfully.

**Comment by joshuawagner** [comment]
Oops, forgot to follow up on that one. Now it's been so long I can't even remember what the problem was. :) Working fine now. Thanks for the update!
